k8sWorkers:
  hosts: 
    k8s-worker-1:
      ansible_host: '{{lookup('env', 'K8S-WORKER-1')}}'
    k8s-worker-2:
      ansible_host: '{{lookup('env', 'K8S-WORKER-2')}}'

k8sMasters:
  hosts:
    k8s-master:
      ansible_host: '{{lookup('env', 'K8S-MASTER')}}'

