#containerd
- name: create /etc/containerd folder if not exists
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    mode: '0755'

- name: print containerd config
  ansible.builtin.shell: containerd config default
  register: containerd_conf_output

- name: save containerd config to config.toml
  ansible.builtin.copy:
    content: "{{ containerd_conf_output.stdout }}"
    dest: /etc/containerd/config.toml
    force: yes

- name: configure systemd cgroup driver
  ansible.builtin.lineinfile:
    path: /etc/containerd/config.toml
    regexp: '^(\s*)SystemdCgroup = false$'
    line: '\g<1>SystemdCgroup = true'
    backrefs: yes
  notify:
    - restart systemd
