# kernel settings
- name: check if k8s.conf exists
  stat:
    path: /etc/modules-load.d/k8s.conf
  register: modules_k8s_conf

- name: create k8s.conf
  ansible.builtin.lineinfile:
    path: /etc/modules-load.d/k8s.conf
    line: |
      overlay
      br_netfilter
    create: yes
    mode: 0644
  when: not modules_k8s_conf.stat.exists

- name: load overlay kernel module
  community.general.modprobe:
    name: overlay
    state: present

- name: load br_netfilter kernel module
  community.general.modprobe:
    name: br_netfilter
    state: present

- name: check if k8s.conf exists
  stat:
    path: /etc/sysctl.d/k8s.conf
  register: sysctl_k8s_conf

- name: sysctl params
  ansible.builtin.lineinfile:
    path: /etc/sysctl.d/k8s.conf
    line: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1
    create: yes
    mode: 0644
  when: not sysctl_k8s_conf.stat.exists
  notify: apply sysctl params

  