# install k8s components
- name: install prerequisites for k8s components
  ansible.builtin.import_tasks: prerequisites.yaml

- name: add repositories
  ansible.builtin.import_tasks: repositories.yaml

- name: update & upgrade
  ansible.builtin.import_role:
    name: common

- name: install k8s components
  ansible.builtin.import_tasks: k8s-components.yaml

