# get join token
- name: print token
  ansible.builtin.shell: kubeadm token create --print-join-command
  register: token

- name: write token to file
  ansible.builtin.copy:
    content: "{{ token.stdout }}"
    dest: /tmp/token

- name: copy token file to control host
  ansible.builtin.fetch:
    src: /tmp/token
    dest: '{{ token_path }}'
    flat: yes
    
- name: delete join token on remote node
  ansible.builtin.file:
    path: /tmp/token
    state: absent