# install & configure containerd 
- name: create k8s.conf
  ansible.builtin.shell: |
    cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
    overlay
    br_netfilter
    EOF

- name: sudo modprobe overlay
  ansible.builtin.command: sudo modprobe overlay 

- name: sudo modprobe br_netfilter
  ansible.builtin.command: sudo modprobe br_netfilter

- name: sysctl params
  ansible.builtin.shell: |
    cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
    net.bridge.bridge-nf-call-iptables  = 1
    net.bridge.bridge-nf-call-ip6tables = 1
    net.ipv4.ip_forward                 = 1
    EOF

- name: apply sysctl params without reboot
  ansible.builtin.command: sudo sysctl --system

- name: install containerd package
  ansible.builtin.apt:
    name: containerd
    state: latest

- name: check if /etc/containerd exists
  stat:
    path: "/etc/containerd"
  register: containerd_folder

- name: create /etc/containerd folder
  ansible.builtin.command: sudo mkdir /etc/containerd
  when: not containerd_folder.stat.exists

- name: create containerd config file
  ansible.builtin.shell: containerd config default | sudo tee /etc/containerd/config.toml

- name: configure systemd cgroup driver
  ansible.builtin.command: sudo sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml

- name: load new configuration
  ansible.builtin.command: sudo systemctl restart containerd

