- name: setup nodes for K8s
  hosts: all
  become: yes
  tasks:
    - name: update & upgrade system
      ansible.builtin.import_tasks: update.yaml
    - name: install containerd
      ansible.builtin.import_tasks: install-containerd.yaml
    - name: install k8s components
      ansible.builtin.import_tasks: install-k8s-components.yaml


- name: configure k8s master
  hosts: k8sMasters
  become: yes
  tasks:
    - name: bootstrap k8s cluster
      ansible.builtin.shell: kubeadm init | tee ~/kubeadm-output.txt
    - name: get join token
      ansible.builtin.shell: kubeadm token create --print-join-command
      register: join_token
    - name: write token to file
      ansible.builtin.copy:
        content: "{{ join_token.stdout }}"
        dest: ~/join_token
    - name: copy token file to control host
      ansible.builtin.fetch:
        src: ~/join_token
        dest: join_token
        flat: yes
    - name: delete join token on remote node
      ansible.builtin.file:
        path: ~/join_token
        state: absent


- name: configure k8s-workers
  hosts: k8sWorkers
  become: yes
  tasks:
    - name: copy token
      ansible.builtin.copy:
        src: join_token
        dest: ~/jt
    - name: read token
      ansible.builtin.slurp:
        src: ~/jt
      register: join_token_file
    - name: join to cluster
      ansible.builtin.debug: 
        msg: "{{ join_token_file['content'] | b64decode }}"
    - name: remove token file
      ansible.builtin.file:
        path: ~/jt
        state: absent