# add repositories
- name: check if docker gpg exists
  stat:
    path: "/etc/apt/trusted.gpg.d/docker.gpg"
  register: docker

- name: fetch docker repository
  ansible.builtin.shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg |  gpg --dearmour -o /etc/apt/trusted.gpg.d/docker.gpg
  when: not docker.stat.exists

- name: add docker repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu jammy stable
    state: present
  when: not docker.stat.exists